check-for-updates: true

# Placeholders are allowed in all messages
chat:
  format: "<teal>%Player_name% <lavender>» <text>{message}"
  join-message: "<peach>%Player_name%<text> has joined the game!"
  quit-message: "<peach>%Player_name%<text> has left the game!"
  welcome-message: "<lavender>Welcome to the server, <peach>%Player_name%<text>!"
  settings:
    only-ascii: false
    pings:
      enabled: true
      format: "<peach>@<player><reset><text>"
      ding: true
    broadcast:
      format: "<red><bold>Broadcast<reset> <peach>» <text>"
    alert:
      location: "title" # "action_bar", "title", "chat"
      title: "<red><bold>ALERT<reset>"
      subtitle: "<peach>{message}"
  channels:
    global:
      format: "<teal>%Player_name% <lavender>» <text>{message}"
      permission: "none"
      default: true
      receives:
        - "staff"
    staff:
      format: "<red><bold>STAFFCHAT<reset> <peach>%Player_name% <lavender>» <text>{message}"
      permission: "chat.staff"

messages:
  no-recent-messages: "<red>There is no one to reply to!"
  player-not-found: "<red>The player <peach><player><reset><red> was not found!"
  player-not-online: "<red>The player <peach><player><reset><red> is not online!"
  you-have-ignored: "<red>You cannot send messages to <peach><player><reset><red> because you have ignored them!"
  may-not-ignore: "<red>You may not ignore <peach><player><reset><red>!"
  only-ascii: "<red>Only <peach>ASCII<reset><red> characters are allowed in names!"
  no-permission: "<red>You don't have permission to do that!"
  no-console: "<red>You can't do that from the console!"
  channel-does-not-exist: "<red>The channel <peach><channel><reset><red> does not exist!"
  no-permission-to-join-channel: "<red>You don't have permission to join the channel <peach><channel><reset><red>!"
  already-in-channel: "<red>You are already in the channel <peach><channel><reset><red>!"
  joined-channel: "<green>You have joined the channel <peach><channel><reset><green>!"
  may-not-whois: "<red>You may not use <teal>/whois<red> on <peach><player><reset><red>!"
  