name: chatcore
version: '0.0.2'
main: us.km127pl.chatcore.ChatCore
api-version: "1.20"
author: km127pl
description: ChatCore plugin for Paper
depend:
  - PlaceholderAPI
commands:
  chatcore:
    description: ChatCore plugin command
    usage: /<command> [reload]
  msg:
    description: Send a private message to a player
    usage: /<command> <player> <message>
  r:
    description: Reply to a private message
    usage: /<command> <message>
  ignore:
    description: Ignore a player
    usage: /<command> <player>
  unignore:
    description: Unignore a player
    usage: /<command> <player>
  broadcast:
    description: Broadcast a message
    usage: /<command> <message>
  whois:
    description: Get information about a player
    usage: /<command> <player>
  chat:
    description: Change your chat channel
    usage: /<command> <channel>
